config/routes.rb
=begin
RedmineApp::Application.routes.draw do
#Rails::application::routes.draw do |map|
  scope '/projects/:project_id/metrics' do
    resources :checkpoints, :controller => 'checkpoints' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

  scope '/projects/:project_id/metrics' do
    resources :expenditures, :controller => 'expenditures' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

resources :history_user_profile

#  resources :checkpoints,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
#  resources :expenditures,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
  match '/projects/:project_id/metrics/:action' => 'metrics', :as => :metrics
  match '/management/:action' => 'management', :as => :management
  match '/admin/cost_history' => 'admin#cost_history', :as => :cost_history
  match '/history_profiles_cost/:action' => 'history_profiles_cost'
  #match '/history_user_profile/:action' => 'history_user_profile'
  #match '/history_user_profile/edit/:id' => 'history_user_profile#edit'


#  map.metrics '/projects/:project_id/metrics/:action', :controller => 'metrics'
#  map.management '/management/:action', :controller => 'management'
#  map.cost_history '/admin/cost_history', :controller => 'admin', :action => 'cost_history'
  match '/settings/show_tracker_custom_fields' => 'settings#show_tracker_custom_fields'
end
=end
resources :hr_profiles
resources :hr_profiles_categories
resources :hr_profiles_costs, only: [:index]
#resources :hr_user_profiles
resources :users do
  resources :hr_user_profiles
end
#match "hr_profiles_costs", :to => "hr_profiles_costs#index", :via => [:get]
match "hr_profiles_costs/create_year", :to => "hr_profiles_costs#create_year", :via => [:post]
match "hr_profiles_costs/edit_year/:year", :to => "hr_profiles_costs#edit_year", :via => [:get], :as => 'hr_profiles_costs_edit_year'
match "hr_profiles_costs/update_year/:year", :to => "hr_profiles_costs#update_year", :via => [:put], :as => 'hr_profiles_costs_update_year'
match "hr_profiles_costs/destroy_year/:year", :to => "hr_profiles_costs#destroy_year", :via => [:delete]

app/views/users/_edit_user_profile_row.html.erb
<%= fields_for "hr_user_profile[]", p do |f| %>
	<td><%= f.select :hr_profile_id, options_from_collection_for_select(HrProfile.all, :id, :name, p.hr_profile_id), :include_blank => true %></td>
	<td><%= f.text_field :start_date, :id => 'hr_user_profile_start_date_'+p.id.to_s %><%= calendar_for('hr_user_profile_start_date_'+p.id.to_s) %></td>
	<td>
		<%=l('hr.label_onwards') %>
	    <%= check_box_tag 'onwards['+p.id.to_s+']', 'yes', p.end_date.nil?, :class => 'onwards' %>
	    <%= f.text_field :end_date, :id => 'hr_user_profile_end_date_'+p.id.to_s, :class => 'end_date', :disabled => p.end_date.nil? %><%= calendar_for('hr_user_profile_end_date_'+p.id.to_s) if p.end_date.present? %>
	</td>
	<td class="buttons">
		<%= link_to l(:button_save), "#", :onclick => "$('#edit_hr_user_profile_form').prop('action','"+user_hr_user_profile_path(@user, p)+"').submit()", :class => 'icon icon-save' %>
		<%= delete_link user_hr_user_profile_path(@user, p), :remote => true %>
	</td>
<% end %>

app/views/users/_profile.html.erb
<% content_for :header_tags do %>
  <%= javascript_include_tag "user_profiles.js", :plugin => 'redmine_hr' %>
<% end %>

<% profile_list = HrUserProfile.where(user_id: @user.id).order(:start_date) %>
<div>
<%= form_tag user_hr_user_profiles_path(@user), remote: true, :method => :put, :id => 'edit_hr_user_profile_form' do %> 
    <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
    <table class="list memberships">
    	<thead>
    	  <th><%= l(:'hr.label_profile_plural') %></th>
    	  <th><%= l(:field_start_date) %></th>
    	  <th><%= l(:field_end_date) %></th>
        <th></th>
    	</thead>
    	<tbody>
        <% profile_list.each do |p| %>
          <tr class="<%= cycle 'odd', 'even' %>" data-id="<%=p.id%>">
            <%= render :partial => 'user_profile_row', :locals => {:p => p} %>
          </tr>
        <% end %>
    	</tbody>
    </table>
<% end %>
  <br>

  <% hr_user_profile = params[:hr_user_profile].present? ? HrUserProfile.new(params.require(:hr_user_profile).permit(:user_id, :hr_profile_id, :start_date, :end_date, :onwards)) : HrUserProfile.new %>
  <div id="new_history_user_profile">
    <%= form_for [@user, hr_user_profile] do |f| %>
      <fieldset class="box tabular">
        <legend><%= l('hr.label_profile_new') %></legend>
        <p>
          <%= f.label :hr_profile_id, l(:'hr.label_profile_plural') %>
          <%= f.select :hr_profile_id, options_from_collection_for_select(HrProfile.all, :id, :name, hr_user_profile[:hr_profile_id]), :include_blank => true %>
        </p>
        <p>
          <%= f.label :start_date, l(:field_start_date) %>
          <%= f.text_field :start_date %><%= calendar_for('hr_user_profile_start_date') %>
        </p>
        <p>
          <%= f.label :onwards, l(:'hr.label_onwards') %>
          <%= check_box_tag 'onwards', 'yes', (params[:onwards].present? and params[:onwards] == "yes"), :class => 'onwards' %>
        </p>
        <p>
          <%= f.label :end_date, l(:field_end_date) %>
          <%= f.text_field :end_date, :class => 'end_date' %>
        </p>
      </fieldset>
      <div><%= f.submit l(:button_submit) %></div>
    <% end %>
  </div>
</div>

app/views/users/_user_profile_row.html.erb
<td><%= p.profile.name %></td>
<td><%= p.start_date.present? ? p.start_date.strftime('%Y-%m-%d') : "--" %></td>
<td><%= p.end_date.present? ? p.end_date.strftime('%Y-%m-%d') : l('hr.label_onwards') %></td>
<td class="buttons">
<%= link_to l(:button_edit), edit_user_hr_user_profile_path(@user, p.id), :class => 'icon icon-edit', :remote => true %>
<%= delete_link user_hr_user_profile_path(@user, p), :remote => true %>
</td>