config/routes.rb
=begin
RedmineApp::Application.routes.draw do
#Rails::application::routes.draw do |map|
  scope '/projects/:project_id/metrics' do
    resources :checkpoints, :controller => 'checkpoints' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

  scope '/projects/:project_id/metrics' do
    resources :expenditures, :controller => 'expenditures' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

resources :history_user_profile

#  resources :checkpoints,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
#  resources :expenditures,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
  match '/projects/:project_id/metrics/:action' => 'metrics', :as => :metrics
  match '/management/:action' => 'management', :as => :management
  match '/admin/cost_history' => 'admin#cost_history', :as => :cost_history
  match '/history_profiles_cost/:action' => 'history_profiles_cost'
  #match '/history_user_profile/:action' => 'history_user_profile'
  #match '/history_user_profile/edit/:id' => 'history_user_profile#edit'


#  map.metrics '/projects/:project_id/metrics/:action', :controller => 'metrics'
#  map.management '/management/:action', :controller => 'management'
#  map.cost_history '/admin/cost_history', :controller => 'admin', :action => 'cost_history'
  match '/settings/show_tracker_custom_fields' => 'settings#show_tracker_custom_fields'
end
=end
resources :hr_profiles
resources :hr_profiles_categories
resources :hr_profiles_costs, only: [:index]
#resources :hr_user_profiles
resources :users do
  resources :hr_user_profiles
end
#match "hr_profiles_costs", :to => "hr_profiles_costs#index", :via => [:get]
match "hr_profiles_costs/create_year", :to => "hr_profiles_costs#create_year", :via => [:post]
match "hr_profiles_costs/edit_year/:year", :to => "hr_profiles_costs#edit_year", :via => [:get], :as => 'hr_profiles_costs_edit_year'
match "hr_profiles_costs/update_year/:year", :to => "hr_profiles_costs#update_year", :via => [:put], :as => 'hr_profiles_costs_update_year'
match "hr_profiles_costs/destroy_year/:year", :to => "hr_profiles_costs#destroy_year", :via => [:delete]

app/models/hr_profiles_cost.rb
class HrProfilesCost < ActiveRecord::Base
	
	belongs_to :profile, class_name: "HrProfile", foreign_key: "hr_profile_id"
  has_many :time_entries, ->(hpc) { where("tyear = ?", hpc.year) }, :through => :profile

	validates :hourly_cost, :numericality => { :greater_than_or_equal_to => 0 }, :presence => true

	after_save :save_profile_cost
	after_destroy :destroy_profile_cost

	DEFAULT_HOURLY_COST = 0.0

	def self.years
		select(:year).distinct.map(&:year)
	end

	def get_errors
		errors.present? ? errors.full_messages.map{|m| profile.name+": "+m} : []
	end

	def save_profile_cost
	  if self.hourly_cost_changed?
		  self.time_entries.each do |te|
		  	te.set_profile_and_cost(te.hr_profile_id, self.hourly_cost)
		  end
		end
	end

	def destroy_profile_cost
	  self.time_entries.each do |te|
	  	te.set_profile_and_cost(te.hr_profile_id, DEFAULT_HOURLY_COST)
	  end
	end
end

app/controllers/hr_profiles_costs_controller.rb
class HrProfilesCostsController < ApplicationController
  layout 'admin'
  before_filter :find_profiles, :only => [:index, :edit_year, :update_year]
  before_filter :require_admin
  

  def index
    @year_costs = HrProfilesCost.includes(:profile).where("hr_profile_id IN (?)", @profiles.map(&:id)).group_by(&:year)

    if @year_costs.present?
      @years = @year_costs.keys.sort.reverse
      @next_year = @years.first+1
      @year_options = ((@years.last-5)..(@next_year+5))
    else
      @years = []
      @next_year = Date.today.year
      @year_options = ((@next_year-5)..(@next_year+5))
    end
  end 

  def edit_year
    @year = params[:year]
    @profile_costs = HrProfilesCost.includes(:profile).where(year: @year)

    respond_to do |format|
      format.js
    end
  end

  def update_year
    @year = params[:year]
    @profile_costs = HrProfilesCost.includes(:profile).where(year: @year)
    @message = ""

    HrProfilesCost.transaction do
      errors = HrProfilesCost.update(params[:hr_profiles_cost].keys, params[:hr_profiles_cost].values).map(&:get_errors).flatten

      if errors.present?
        @flash = 'error'
        @message = errors.join('<br>').html_safe
        raise ActiveRecord::Rollback, @message
      else
        @flash = 'notice'
        @message = l(:notice_successful_update)
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def create_year
    data = []

    params[:values].each do |k,v|
      element = {}
      element[:year] = params[:year]
      element[:hr_profile_id] = k
      element[:hourly_cost] = v.present? ? v : HrProfilesCost::DEFAULT_HOURLY_COST
      data << element
    end

    HrProfilesCost.transaction do
      errors = HrProfilesCost.create(data).map(&:get_errors).flatten

      if errors.present?
        message = errors.join('<br>').html_safe
        flash['error'] = message
        raise ActiveRecord::Rollback, message
      else
        flash['notice'] = l(:notice_successful_create)
      end
    end

    redirect_to :action => 'index'
  end

  def destroy_year
    HrProfilesCost.transaction do
      errors = HrProfilesCost.destroy_all(year: params[:year]).map(&:get_errors).flatten

      if errors.present? or HrProfilesCost.where(year: params[:year]).present?
        message = errors.present? ? errors.join('<br>').html_safe : l(:"hr.error_unable_destroy")
        flash['error'] = message
        raise ActiveRecord::Rollback, message
      else
        flash['notice']= l(:notice_successful_delete)
      end
    end
    
    redirect_to :action => 'index'
  end

  private
  def find_profiles
    @profiles = params[:profile_category].present? ? HrProfile.category(params[:profile_category]).order(:id) : HrProfile.all.order(:id)
  end
end

app/views/hr_profiles_costs/_content.html.erb
<%= form_tag hr_profiles_costs_update_year_path(@years.first), remote: true, :method => :put, :id => 'hr_profiles_costs_update_year_form' do %>
<table class="list">
  <tr class="<%= cycle 'odd', 'even' %>">
    <td></td>
    <% @profiles.each do |profile| %>
      <th><%=h profile.name %></th>
    <% end %>
    <th></th>
  </tr>
  <% @years.each do |year| %>
    <% profile_costs = @year_costs[year] %>
    <tr class="<%= cycle 'odd', 'even' %>" data-year="<%=year%>">
      <%= render :partial => 'profile_cost_row', :locals => {:year => year, :profile_costs => profile_costs} %>
    </tr>
  <% end %>
</table>
<% end %>

app/views/hr_profiles_costs/_edit_profile_cost_row.html.erb
<th class="center"><%= year %></th>
<% @profiles.each do |profile| %>
<% profile_cost = profile_costs.find{|c|c.profile.name == profile.name} %>
<% cost = begin profile_cost.hourly_cost rescue HrProfilesCost::DEFAULT_HOURLY_COST.to_s end %>
  <%= fields_for "hr_profiles_cost[]", profile_cost do |f| %>
	  <td class="center editable"><%= currency (f.text_field :hourly_cost, :size => 1).html_safe %></td>
	<% end %>
<% end %>
<td class='buttons'>
	<%= link_to l(:button_save), "#", :onclick => "$('#hr_profiles_costs_update_year_form').prop('action','"+hr_profiles_costs_update_year_path(:year => year, :profile_category => params[:profile_category])+"').submit()", :class => 'icon icon-save' %>
  <%= link_to l(:button_delete), {:controller => 'hr_profiles_costs', :action => 'destroy_year', :year => year}, :data => {:confirm => l(:text_are_you_sure)}, :class => 'icon icon-del', :method => :delete %>
</td>

app/views/hr_profiles_costs/_new_year.html.erb
<div id="new_history_profiles_cost">
  <%= form_tag controller: 'hr_profiles_costs', action: 'create_year' do %>
    <fieldset class="box tabular">
      <legend><%= l('hr.label_add_year') %></legend>
      <p>
        <label><%=l(:label_year)%></label>
        <%= select_tag 'year', options_for_select(@year_options, selected: @next_year, disabled: @years) %>
      </p>

      <% @profiles.group_by(&:category).each do |category, profiles| %>
        <fieldset class="box tabular">
        <legend><%=category.present? ? category.name : 'Sin categoría'%></legend>
        <div class='splitcontentleft'>
          <% for i in (0..profiles.count-1).step(2) %>
            <% profile = profiles[i] %>
            <p>
              <%= label_tag profile.name %>
              <%= text_field_tag 'values['+profile.id.to_s+']', '', size: 10 %>
            </p>
          <% end %>
        </div>

        <div class='splitcontentright'>
          <% for i in (1..profiles.count-1).step(2) %>
            <% profile = profiles[i] %>
            <p>
              <%= label_tag profile.name %>
              <%= text_field_tag 'values['+profile.id.to_s+']', '', size: 10 %>
            </p>
          <% end %>
        </div>
        </fieldset>
      <% end %>
      <div style="clear:both;"></div>
    </fieldset>
    <%= submit_tag l(:"button_create") %>
  <% end %>
</div>

app/views/hr_profiles_costs/_profile_cost_row.html.erb
<th class="center"><%= year %></th>
<% @profiles.each do |profile| %>
  <% profile_cost = profile_costs.find{|c| c.profile.id == profile.id} %>
  <% cost = begin profile_cost.hourly_cost rescue HrProfilesCost::DEFAULT_HOURLY_COST.to_s end %>
  <td class="center editable"><%= currency ("<span class='"+profile_cost.id.to_s+"'>"+cost.to_s+"</span>").html_safe %></td>
<% end %>
<td class='buttons'>
	<%= link_to l(:button_edit), hr_profiles_costs_edit_year_path(:year => year, :profile_category => params[:profile_category]), :class => 'icon icon-edit', :remote => true %>
  <%= link_to l(:button_delete), {:controller => 'hr_profiles_costs', :action => 'destroy_year', :year => year}, :data => {:confirm => l(:text_are_you_sure)}, :class => 'icon icon-del', :method => :delete %>
</td>

app/views/hr_profiles_costs/destroy_year.js.erb
<% if @flash == 'notice' %>
$('tr[data-year="<%=@year%>"]').remove();
$('tr:even').removeClass('odd').addClass('even');
$('tr:odd').removeClass('even').addClass('odd');
<% end %>

$('.flash').remove();
div = "<div class='flash <%=@flash%>' id='flash_<%=@flash%>'><%=@message%></div>"
$('#content').prepend(div);

app/views/hr_profiles_costs/edit_year.js.erb
$('tr[data-year="<%=@year.to_s%>"]').html("<%= escape_javascript(render :partial => 'edit_profile_cost_row', :locals => {:year => @year, :profile_costs => @profile_costs}) %>");

app/views/hr_profiles_costs/index.html.erb
<h2><%=l('hr.label_cost_history')%></h2>
<%= form_tag hr_profiles_costs_path, :method => :get do %>
<%= label :profile_category, l(:"hr.label_category") %>:
<%= select_tag :profile_category, options_from_collection_for_select(HrProfilesCategory.all, "id", "name", params[:profile_category]), :prompt => l(:"hr.label_all"), :onchange => "$(this).closest('form').submit();" %>
<% end %>
<% if @years.present? %>
<%= render :partial => 'content' %>
<% end %>
<%= render :partial => 'new_year' %>

app/views/hr_profiles_costs/update_year.js.erb
<% if @flash == 'notice' %>
$('tr[data-year="<%=@year.to_s%>"]').html("<%= escape_javascript(render :partial => 'profile_cost_row', :locals => {:year => @year, :profile_costs => @profile_costs}) %>");
<% end %>

$('.flash').remove();
div = "<div class='flash <%=@flash%>' id='flash_<%=@flash%>'><%=@message%></div>"
$('#content').prepend(div);