config/routes.rb
=begin
RedmineApp::Application.routes.draw do
#Rails::application::routes.draw do |map|
  scope '/projects/:project_id/metrics' do
    resources :checkpoints, :controller => 'checkpoints' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

  scope '/projects/:project_id/metrics' do
    resources :expenditures, :controller => 'expenditures' do
      member do
        post :new_journal
        post :edit_journal
        get  :edit_journal
      end
      collection do
        put :preview
      end
    end
  end

resources :history_user_profile

#  resources :checkpoints,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
#  resources :expenditures,
#                :path_prefix => '/projects/:project_id/metrics',
#                :member => { :new_journal => :post, :edit_journal => [:get, :post] },
#                :collection => { :preview => :put }
  match '/projects/:project_id/metrics/:action' => 'metrics', :as => :metrics
  match '/management/:action' => 'management', :as => :management
  match '/admin/cost_history' => 'admin#cost_history', :as => :cost_history
  match '/history_profiles_cost/:action' => 'history_profiles_cost'
  #match '/history_user_profile/:action' => 'history_user_profile'
  #match '/history_user_profile/edit/:id' => 'history_user_profile#edit'


#  map.metrics '/projects/:project_id/metrics/:action', :controller => 'metrics'
#  map.management '/management/:action', :controller => 'management'
#  map.cost_history '/admin/cost_history', :controller => 'admin', :action => 'cost_history'
  match '/settings/show_tracker_custom_fields' => 'settings#show_tracker_custom_fields'
end
=end
resources :hr_profiles
resources :hr_profiles_categories
resources :hr_profiles_costs, only: [:index]
#resources :hr_user_profiles
resources :users do
  resources :hr_user_profiles
end
#match "hr_profiles_costs", :to => "hr_profiles_costs#index", :via => [:get]
match "hr_profiles_costs/create_year", :to => "hr_profiles_costs#create_year", :via => [:post]
match "hr_profiles_costs/edit_year/:year", :to => "hr_profiles_costs#edit_year", :via => [:get], :as => 'hr_profiles_costs_edit_year'
match "hr_profiles_costs/update_year/:year", :to => "hr_profiles_costs#update_year", :via => [:put], :as => 'hr_profiles_costs_update_year'
match "hr_profiles_costs/destroy_year/:year", :to => "hr_profiles_costs#destroy_year", :via => [:delete]

app/models/hr_profile.rb
class HrProfile < ActiveRecord::Base
	has_many :costs, class_name: "HrProfilesCost", foreign_key: "hr_profile_id", :dependent => :destroy
	has_many :user_profiles, class_name: "HrUserProfile", foreign_key: "hr_profile_id", :dependent => :destroy
	belongs_to :category, class_name: "HrProfilesCategory", foreign_key: "hr_profiles_category_id"
	has_many :users, -> { where "hr_user_profiles.end_date is ?", nil}, :through => :user_profiles
	has_many :time_entries, dependent: :nullify

	validates_presence_of :name
  validates_length_of :name, :maximum => 20

  after_create :create_costs

  scope :category, -> (id) { where(hr_profiles_category_id: id) }

	def cost_on(year)
		begin
			if costs.where(year: year).present?
				costs.where(year: year).first.hourly_cost
			else
				costs.where("year <= ?", year).order('year DESC').first.hourly_cost
			end
		rescue
			HrProfilesCost::DEFAULT_HOURLY_COST
		end
	end

	private
	def create_costs
		HrProfilesCost.years.each do |year|
			costs << HrProfilesCost.new(year: year, hourly_cost: HrProfilesCost::DEFAULT_HOURLY_COST)
		end
	end
end

app/controllers/hr_profiles_controller.rb
class HrProfilesController < ApplicationController
  layout 'admin'
  before_filter :require_admin

  def index
    @profiles = HrProfile.all.order(:id)
    @categories = HrProfilesCategory.all.order(:id)
  end

  def new
    @profile = HrProfile.new
    @categories = HrProfilesCategory.all
  end

  def create
    @profile = HrProfile.new(profile_params)
    if @profile.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to hr_profiles_path
    else
      @categories = HrProfilesCategory.all
      render :action => 'new'
    end
  end

  def edit
    @profile = HrProfile.find(params[:id])
    @categories = HrProfilesCategory.all
  end

  def update
    @profile = HrProfile.find(params[:id])
    if @profile.update_attributes(profile_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to hr_profiles_path(:page => params[:page])
    else
      render :action => 'edit'
    end
  end

  def destroy
    HrProfile.find(params[:id]).destroy
    redirect_to hr_profiles_path
  rescue
    flash[:error] = l(:"hr.error_unable_delete_profile")
    redirect_to hr_profiles_path
  end

  private
  def profile_params
    params.require(:hr_profile).permit(:name, :hr_profiles_category_id)
  end
end

app/views/hr_profiles/_form.html.erb
<%= error_messages_for @profile %>

<div class="box tabular">
<p><%= f.text_field :name, :required => true %></p>
<p><%= f.select :hr_profiles_category_id, options_from_collection_for_select(@categories, :id, :name), :include_blank => true %></p>
</div>

app/views/hr_profiles/edit.html.erb
<%= title [l(:"hr.label_profile_plural"), hr_profiles_path], @profile.name %>

<%= labelled_form_for @profile do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/hr_profiles/index.html.erb
<h2><%=l('hr.label_profile_management')%></h2>
<div class="splitcontentleft">
  <div class="contextual">
  <%= link_to l(:"hr.label_profile_new"), new_hr_profile_path, :class => 'icon icon-add' %>
  </div>

  <h3><%=l('hr.label_profile_plural')%></h3>

  <table class="list">
  <tr class="<%= cycle 'odd', 'even' %>">
    <th><%=l(:field_name)%></th>
    <th><%=l(:field_category)%></th>
    <th></th>
  </tr>

  <% @profiles.each do |profile| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td class='name'><%= link_to profile.name, edit_hr_profile_path(profile.id) %></td>
    <td class='center'><%= begin profile.category.name rescue "-" end %></td>
    <td class='buttons'>
      <%= delete_link hr_profile_path(profile.id) %>
    </td>
  </tr>
  <% end %>
  </table>
</div>

<div class="splitcontentright">
  <div class="contextual">
  <%= link_to l(:"hr.label_profile_category_new"), new_hr_profiles_category_path, :class => 'icon icon-add' %>
  </div>

  <h3><%=l('hr.label_profiles_category_plural')%></h3>

  <table class="list">
  <tr class="<%= cycle 'odd', 'even' %>">
    <th><%=l(:field_name)%></th>
    <th></th>
  </tr>

  <% @categories.each do |category| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <td class='name'><%= link_to category.name, edit_hr_profiles_category_path(category.id) %></td>
    <td class='buttons'>
      <%= delete_link hr_profiles_category_path(category.id) %>
    </td>
  </tr>
  <% end %>
  </table>
</div>

app/views/hr_profiles/new.html.erb
<%= title [l(:"hr.label_profile_plural"), hr_profiles_path], l(:"hr.label_profile_new") %>

<%= labelled_form_for @profile do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>